name: gold_card_editer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_image_compress: ^2.4.0
  image: ^4.5.3
  image_editor: ^1.6.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  saver_gallery: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
